DROP TABLE IF EXISTS usuario_cargo CASCADE;
DROP TABLE IF EXISTS cargo CASCADE;
DROP SEQUENCE IF EXISTS seq_cargo;

DROP TABLE IF EXISTS usuarios CASCADE;

CREATE TABLE usuarios (
    id_usuario VARCHAR(255) PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    foto VARCHAR(255),
    role VARCHAR(50) NOT NULL DEFAULT 'USER'
);
